//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace SPMReader.Models.ModelDescription {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/ModelDescription.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:SPMReader/ModelDescription.xsd", IsNullable=false)]
    public abstract partial class Model {
        
        private ModelDescription modelDescriptionField;
        
        /// <remarks/>
        public ModelDescription ModelDescription {
            get {
                return this.modelDescriptionField;
            }
            set {
                this.modelDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/ModelDescription.xsd")]
    public partial class ModelDescription {
        
        private string prefixModelTextField;
        
        private string postfixModelTextField;
        
        private string eOFMarkerTextField;
        
        private string newLineMarkerField;
        
        public ModelDescription() {
            this.eOFMarkerTextField = "*EOF*";
        }
        
        /// <remarks/>
        public string PrefixModelText {
            get {
                return this.prefixModelTextField;
            }
            set {
                this.prefixModelTextField = value;
            }
        }
        
        /// <remarks/>
        public string PostfixModelText {
            get {
                return this.postfixModelTextField;
            }
            set {
                this.postfixModelTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("*EOF*")]
        public string EOFMarkerText {
            get {
                return this.eOFMarkerTextField;
            }
            set {
                this.eOFMarkerTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewLineMarker {
            get {
                return this.newLineMarkerField;
            }
            set {
                this.newLineMarkerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/ModelDescription.xsd")]
    public partial class Descriptor {
        
        private string separatorStyleField;
        
        private bool isStringField;
        
        private string attributeNameField;
        
        private bool valueHasPreceedingSpaceField;
        
        private string prefixValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SeparatorStyle {
            get {
                return this.separatorStyleField;
            }
            set {
                this.separatorStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsString {
            get {
                return this.isStringField;
            }
            set {
                this.isStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ValueHasPreceedingSpace {
            get {
                return this.valueHasPreceedingSpaceField;
            }
            set {
                this.valueHasPreceedingSpaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PrefixValue {
            get {
                return this.prefixValueField;
            }
            set {
                this.prefixValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/ModelDescription.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:SPMReader/ModelDescription.xsd", IsNullable=false)]
    public abstract partial class ComplexType {
        
        private Descriptor[] attributeDescriptorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Descriptor[] AttributeDescriptors {
            get {
                return this.attributeDescriptorsField;
            }
            set {
                this.attributeDescriptorsField = value;
            }
        }
    }
}
