//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace SPMReader.Models.Spektrum.DX8 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("SPM", Namespace="urn:SPMReader/Spektrum/Spektrum.xsd", IsNullable=false)]
    public partial class SpektrumModel : Model {
        
        private SpektrumInformation spektrumField;
        
        private ComplexType[] itemsField;
        
        private Configuration configField;
        
        private Trainer trainerField;
        
        private FlightMode fModeField;
        
        private Analog[] analogField;
        
        private IndexToSourceID[] specialField;
        
        private IndexToSourceID[] softSwField;
        
        private IndexToSourceID[] trimIDField;
        
        private Digital[] digitalField;
        
        private Trim[] trimField;
        
        private Servo[] servoField;
        
        private DualRateExpo[] dR_ExpoField;
        
        private PMix[] pMixField;
        
        private ThrottleCut throCutField;
        
        private ThrottleCurve throCurveField;
        
        private Warning warningField;
        
        private Timer[] timerField;
        
        private Telemetry telemetryField;
        
        /// <remarks/>
        public SpektrumInformation Spektrum {
            get {
                return this.spektrumField;
            }
            set {
                this.spektrumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Acro", typeof(Acrobatic))]
        [System.Xml.Serialization.XmlElementAttribute("C-Mix", typeof(CMix))]
        [System.Xml.Serialization.XmlElementAttribute("EF-Mix", typeof(ElevatorFlapMxing))]
        [System.Xml.Serialization.XmlElementAttribute("Governor", typeof(Governor))]
        [System.Xml.Serialization.XmlElementAttribute("Gyro", typeof(Gyro))]
        [System.Xml.Serialization.XmlElementAttribute("Heli", typeof(Helicopter))]
        [System.Xml.Serialization.XmlElementAttribute("PitchCurve", typeof(PitchCurve))]
        [System.Xml.Serialization.XmlElementAttribute("RevoCurve", typeof(RevoCurve))]
        [System.Xml.Serialization.XmlElementAttribute("S-Mix", typeof(SMix))]
        [System.Xml.Serialization.XmlElementAttribute("SwashPlate", typeof(SwashPlate))]
        public ComplexType[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public Configuration Config {
            get {
                return this.configField;
            }
            set {
                this.configField = value;
            }
        }
        
        /// <remarks/>
        public Trainer Trainer {
            get {
                return this.trainerField;
            }
            set {
                this.trainerField = value;
            }
        }
        
        /// <remarks/>
        public FlightMode FMode {
            get {
                return this.fModeField;
            }
            set {
                this.fModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Analog")]
        public Analog[] Analog {
            get {
                return this.analogField;
            }
            set {
                this.analogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Special")]
        public IndexToSourceID[] Special {
            get {
                return this.specialField;
            }
            set {
                this.specialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoftSw")]
        public IndexToSourceID[] SoftSw {
            get {
                return this.softSwField;
            }
            set {
                this.softSwField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TrimID")]
        public IndexToSourceID[] TrimID {
            get {
                return this.trimIDField;
            }
            set {
                this.trimIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Digital")]
        public Digital[] Digital {
            get {
                return this.digitalField;
            }
            set {
                this.digitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Trim")]
        public Trim[] Trim {
            get {
                return this.trimField;
            }
            set {
                this.trimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Servo")]
        public Servo[] Servo {
            get {
                return this.servoField;
            }
            set {
                this.servoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DR_Expo")]
        public DualRateExpo[] DR_Expo {
            get {
                return this.dR_ExpoField;
            }
            set {
                this.dR_ExpoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("P-Mix")]
        public PMix[] PMix {
            get {
                return this.pMixField;
            }
            set {
                this.pMixField = value;
            }
        }
        
        /// <remarks/>
        public ThrottleCut ThroCut {
            get {
                return this.throCutField;
            }
            set {
                this.throCutField = value;
            }
        }
        
        /// <remarks/>
        public ThrottleCurve ThroCurve {
            get {
                return this.throCurveField;
            }
            set {
                this.throCurveField = value;
            }
        }
        
        /// <remarks/>
        public Warning Warning {
            get {
                return this.warningField;
            }
            set {
                this.warningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Timer")]
        public Timer[] Timer {
            get {
                return this.timerField;
            }
            set {
                this.timerField = value;
            }
        }
        
        /// <remarks/>
        public Telemetry Telemetry {
            get {
                return this.telemetryField;
            }
            set {
                this.telemetryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class SpektrumInformation : ComplexType {
        
        private string generatorField;
        
        private string vCodeField;
        
        private string posIndexField;
        
        private string typeField;
        
        private string curveIndexField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VCode {
            get {
                return this.vCodeField;
            }
            set {
                this.vCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PosIndex {
            get {
                return this.posIndexField;
            }
            set {
                this.posIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string curveIndex {
            get {
                return this.curveIndexField;
            }
            set {
                this.curveIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ThrottleCut))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ElevatorFlapItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ElevatorFlapMxing))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Differential))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SwashPlate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SMix))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CMix))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Governor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Gyro))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RevoCurve))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PitchCurve))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Helicopter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Acrobatic))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TelemetryModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FlightLog))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Telemetry))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Timer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Warning))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Servo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Trim))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ThrottleCurve))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PMix))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DualRateExpo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Digital))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IndexToSourceID))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Analog))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FlightMode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Trainer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Configuration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CurveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpektrumInformation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/ModelDescription.xsd")]
    public abstract partial class ComplexType {
        
        private Descriptor[] attributeDescriptorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Descriptor[] AttributeDescriptors {
            get {
                return this.attributeDescriptorsField;
            }
            set {
                this.attributeDescriptorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/ModelDescription.xsd")]
    public partial class Descriptor {
        
        private string separatorStyleField;
        
        private bool isStringField;
        
        private string attributeNameField;
        
        private bool valueHasPreceedingSpaceField;
        
        private string prefixValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SeparatorStyle {
            get {
                return this.separatorStyleField;
            }
            set {
                this.separatorStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsString {
            get {
                return this.isStringField;
            }
            set {
                this.isStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ValueHasPreceedingSpace {
            get {
                return this.valueHasPreceedingSpaceField;
            }
            set {
                this.valueHasPreceedingSpaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PrefixValue {
            get {
                return this.prefixValueField;
            }
            set {
                this.prefixValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/ModelDescription.xsd")]
    public partial class ModelDescription {
        
        private string prefixModelTextField;
        
        private string postfixModelTextField;
        
        private string eOFMarkerTextField;
        
        private string newLineMarkerField;
        
        public ModelDescription() {
            this.eOFMarkerTextField = "*EOF*";
        }
        
        /// <remarks/>
        public string PrefixModelText {
            get {
                return this.prefixModelTextField;
            }
            set {
                this.prefixModelTextField = value;
            }
        }
        
        /// <remarks/>
        public string PostfixModelText {
            get {
                return this.postfixModelTextField;
            }
            set {
                this.postfixModelTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("*EOF*")]
        public string EOFMarkerText {
            get {
                return this.eOFMarkerTextField;
            }
            set {
                this.eOFMarkerTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewLineMarker {
            get {
                return this.newLineMarkerField;
            }
            set {
                this.newLineMarkerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpektrumModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/ModelDescription.xsd")]
    public abstract partial class Model {
        
        private ModelDescription modelDescriptionField;
        
        /// <remarks/>
        public ModelDescription ModelDescription {
            get {
                return this.modelDescriptionField;
            }
            set {
                this.modelDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class ThrottleCut : ComplexType {
        
        private string conditionIDField;
        
        private string percentField;
        
        private string rampSpeedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string percent {
            get {
                return this.percentField;
            }
            set {
                this.percentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string rampSpeed {
            get {
                return this.rampSpeedField;
            }
            set {
                this.rampSpeedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class ElevatorFlapItem : ComplexType {
        
        private string indexField;
        
        private string offsetField;
        
        private string flapLeftField;
        
        private string flapRightField;
        
        private string flonLeftField;
        
        private string flonRightField;
        
        private string tipLeftField;
        
        private string tipRightField;
        
        private string elevatorField;
        
        private string speedField;
        
        private string analogIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string flapLeft {
            get {
                return this.flapLeftField;
            }
            set {
                this.flapLeftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string flapRight {
            get {
                return this.flapRightField;
            }
            set {
                this.flapRightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string flonLeft {
            get {
                return this.flonLeftField;
            }
            set {
                this.flonLeftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string flonRight {
            get {
                return this.flonRightField;
            }
            set {
                this.flonRightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string tipLeft {
            get {
                return this.tipLeftField;
            }
            set {
                this.tipLeftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string tipRight {
            get {
                return this.tipRightField;
            }
            set {
                this.tipRightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string elevator {
            get {
                return this.elevatorField;
            }
            set {
                this.elevatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string analogID {
            get {
                return this.analogIDField;
            }
            set {
                this.analogIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class ElevatorFlapMxing : ComplexType {
        
        private ElevatorFlapItem[] efItemField;
        
        private string conditionIDField;
        
        private string activePositionsField;
        
        private string mixNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("efItem")]
        public ElevatorFlapItem[] efItem {
            get {
                return this.efItemField;
            }
            set {
                this.efItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activePositions {
            get {
                return this.activePositionsField;
            }
            set {
                this.activePositionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mixName {
            get {
                return this.mixNameField;
            }
            set {
                this.mixNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Differential : ComplexType {
        
        private string conditionIDField;
        
        private string rateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class SwashPlate : ComplexType {
        
        private string rateAileronField;
        
        private string rateElevatorField;
        
        private string ratePitchField;
        
        private string eRingField;
        
        private string expoField;
        
        private string rateExpoField;
        
        private string eleCompField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rateAileron {
            get {
                return this.rateAileronField;
            }
            set {
                this.rateAileronField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rateElevator {
            get {
                return this.rateElevatorField;
            }
            set {
                this.rateElevatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ratePitch {
            get {
                return this.ratePitchField;
            }
            set {
                this.ratePitchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("E-Ring")]
        public string ERing {
            get {
                return this.eRingField;
            }
            set {
                this.eRingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Expo {
            get {
                return this.expoField;
            }
            set {
                this.expoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rateExpo {
            get {
                return this.rateExpoField;
            }
            set {
                this.rateExpoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string eleComp {
            get {
                return this.eleCompField;
            }
            set {
                this.eleCompField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class SMix : ComplexType {
        
        private string rateHighAilEleField;
        
        private string rateLowAilEleField;
        
        private string rateHighEleAilField;
        
        private string rateLowEleAilField;
        
        private string activePositionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rateHighAilEle {
            get {
                return this.rateHighAilEleField;
            }
            set {
                this.rateHighAilEleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rateLowAilEle {
            get {
                return this.rateLowAilEleField;
            }
            set {
                this.rateLowAilEleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rateHighEleAil {
            get {
                return this.rateHighEleAilField;
            }
            set {
                this.rateHighEleAilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rateLowEleAil {
            get {
                return this.rateLowEleAilField;
            }
            set {
                this.rateLowEleAilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activePositions {
            get {
                return this.activePositionsField;
            }
            set {
                this.activePositionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class CMix : ComplexType {
        
        private string rateHighAilThrField;
        
        private string rateLowAilThrField;
        
        private string rateHighEleThrField;
        
        private string rateLowEleThrField;
        
        private string rateHighRudThrField;
        
        private string rateLowRudThrField;
        
        private string activePositionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rateHighAilThr {
            get {
                return this.rateHighAilThrField;
            }
            set {
                this.rateHighAilThrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rateLowAilThr {
            get {
                return this.rateLowAilThrField;
            }
            set {
                this.rateLowAilThrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rateHighEleThr {
            get {
                return this.rateHighEleThrField;
            }
            set {
                this.rateHighEleThrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rateLowEleThr {
            get {
                return this.rateLowEleThrField;
            }
            set {
                this.rateLowEleThrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rateHighRudThr {
            get {
                return this.rateHighRudThrField;
            }
            set {
                this.rateHighRudThrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rateLowRudThr {
            get {
                return this.rateLowRudThrField;
            }
            set {
                this.rateLowRudThrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activePositions {
            get {
                return this.activePositionsField;
            }
            set {
                this.activePositionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Governor : ComplexType {
        
        private string sourceIDField;
        
        private string conditionIDField;
        
        private string trimIDField;
        
        private string fpctField;
        
        private string outChanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourceID {
            get {
                return this.sourceIDField;
            }
            set {
                this.sourceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string trimID {
            get {
                return this.trimIDField;
            }
            set {
                this.trimIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fpct {
            get {
                return this.fpctField;
            }
            set {
                this.fpctField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string outChan {
            get {
                return this.outChanField;
            }
            set {
                this.outChanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Gyro : ComplexType {
        
        private string sourceIDField;
        
        private string conditionIDField;
        
        private string trimIDField;
        
        private string fpctField;
        
        private string tailHoldField;
        
        private string outChanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourceID {
            get {
                return this.sourceIDField;
            }
            set {
                this.sourceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string trimID {
            get {
                return this.trimIDField;
            }
            set {
                this.trimIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fpct {
            get {
                return this.fpctField;
            }
            set {
                this.fpctField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tailHold {
            get {
                return this.tailHoldField;
            }
            set {
                this.tailHoldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string outChan {
            get {
                return this.outChanField;
            }
            set {
                this.outChanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class RevoCurve : ComplexType {
        
        private CurveData[] curvedataField;
        
        private string analogIDField;
        
        private string conditionIDField;
        
        private string trimIDField;
        
        private string activeMaskField;
        
        private string delayField;
        
        private string assignedCurveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Curvedata")]
        public CurveData[] Curvedata {
            get {
                return this.curvedataField;
            }
            set {
                this.curvedataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string analogID {
            get {
                return this.analogIDField;
            }
            set {
                this.analogIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string trimID {
            get {
                return this.trimIDField;
            }
            set {
                this.trimIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activeMask {
            get {
                return this.activeMaskField;
            }
            set {
                this.activeMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string delay {
            get {
                return this.delayField;
            }
            set {
                this.delayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assignedCurve {
            get {
                return this.assignedCurveField;
            }
            set {
                this.assignedCurveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class CurveData : ComplexType {
        
        private string indexField;
        
        private string pointsField;
        
        private string expoField;
        
        private string trimActiveField;
        
        private string curvedField;
        
        private string xField;
        
        private string yField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string points {
            get {
                return this.pointsField;
            }
            set {
                this.pointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Expo {
            get {
                return this.expoField;
            }
            set {
                this.expoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string trimActive {
            get {
                return this.trimActiveField;
            }
            set {
                this.trimActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string curved {
            get {
                return this.curvedField;
            }
            set {
                this.curvedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class PitchCurve : ComplexType {
        
        private CurveData[] curvedataField;
        
        private string analogIDField;
        
        private string conditionIDField;
        
        private string trimIDField;
        
        private string activeMaskField;
        
        private string delayField;
        
        private string assignedCurveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Curvedata")]
        public CurveData[] Curvedata {
            get {
                return this.curvedataField;
            }
            set {
                this.curvedataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string analogID {
            get {
                return this.analogIDField;
            }
            set {
                this.analogIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string trimID {
            get {
                return this.trimIDField;
            }
            set {
                this.trimIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activeMask {
            get {
                return this.activeMaskField;
            }
            set {
                this.activeMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string delay {
            get {
                return this.delayField;
            }
            set {
                this.delayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assignedCurve {
            get {
                return this.assignedCurveField;
            }
            set {
                this.assignedCurveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Helicopter : ComplexType {
        
        private string swashField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Swash {
            get {
                return this.swashField;
            }
            set {
                this.swashField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Acrobatic : ComplexType {
        
        private string wingField;
        
        private string tailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Wing {
            get {
                return this.wingField;
            }
            set {
                this.wingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tail {
            get {
                return this.tailField;
            }
            set {
                this.tailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class TelemetryModule : ComplexType {
        
        private string deviceField;
        
        private string minTempField;
        
        private string maxTempField;
        
        private string minVoltField;
        
        private string maxVoltField;
        
        private string motorPolesField;
        
        private string gearRatioField;
        
        private string minRPMField;
        
        private string maxRPMField;
        
        private string minAlarmField;
        
        private string maxAlarmField;
        
        private string addressField;
        
        private string displayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string minTemp {
            get {
                return this.minTempField;
            }
            set {
                this.minTempField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string maxTemp {
            get {
                return this.maxTempField;
            }
            set {
                this.maxTempField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string minVolt {
            get {
                return this.minVoltField;
            }
            set {
                this.minVoltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string maxVolt {
            get {
                return this.maxVoltField;
            }
            set {
                this.maxVoltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string motorPoles {
            get {
                return this.motorPolesField;
            }
            set {
                this.motorPolesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string gearRatio {
            get {
                return this.gearRatioField;
            }
            set {
                this.gearRatioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string minRPM {
            get {
                return this.minRPMField;
            }
            set {
                this.minRPMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string maxRPM {
            get {
                return this.maxRPMField;
            }
            set {
                this.maxRPMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string minAlarm {
            get {
                return this.minAlarmField;
            }
            set {
                this.minAlarmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string maxAlarm {
            get {
                return this.maxAlarmField;
            }
            set {
                this.maxAlarmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string display {
            get {
                return this.displayField;
            }
            set {
                this.displayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class FlightLog : ComplexType {
        
        private string fField;
        
        private string hField;
        
        private string aField;
        
        private string bField;
        
        private string rField;
        
        private string lField;
        
        private string frameAlarmField;
        
        private string holdAlarmField;
        
        private string minRxField;
        
        private string maxRxField;
        
        private string rxVoltAlarmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string F {
            get {
                return this.fField;
            }
            set {
                this.fField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string H {
            get {
                return this.hField;
            }
            set {
                this.hField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string A {
            get {
                return this.aField;
            }
            set {
                this.aField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string B {
            get {
                return this.bField;
            }
            set {
                this.bField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string R {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string L {
            get {
                return this.lField;
            }
            set {
                this.lField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FrameAlarm {
            get {
                return this.frameAlarmField;
            }
            set {
                this.frameAlarmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HoldAlarm {
            get {
                return this.holdAlarmField;
            }
            set {
                this.holdAlarmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string minRx {
            get {
                return this.minRxField;
            }
            set {
                this.minRxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string maxRx {
            get {
                return this.maxRxField;
            }
            set {
                this.maxRxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RxVoltAlarm {
            get {
                return this.rxVoltAlarmField;
            }
            set {
                this.rxVoltAlarmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Telemetry : ComplexType {
        
        private FlightLog flightLogField;
        
        private TelemetryModule[] moduleField;
        
        private string lcdModeField;
        
        private string screensField;
        
        /// <remarks/>
        public FlightLog FlightLog {
            get {
                return this.flightLogField;
            }
            set {
                this.flightLogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Module")]
        public TelemetryModule[] Module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string lcdMode {
            get {
                return this.lcdModeField;
            }
            set {
                this.lcdModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Screens {
            get {
                return this.screensField;
            }
            set {
                this.screensField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Timer : ComplexType {
        
        private string indexField;
        
        private string modeField;
        
        private string minutesField;
        
        private string secondsField;
        
        private string oneTimeField;
        
        private string audioField;
        
        private string vibrateField;
        
        private string startIDField;
        
        private string eventField;
        
        private string threshField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Minutes {
            get {
                return this.minutesField;
            }
            set {
                this.minutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string oneTime {
            get {
                return this.oneTimeField;
            }
            set {
                this.oneTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Audio {
            get {
                return this.audioField;
            }
            set {
                this.audioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Vibrate {
            get {
                return this.vibrateField;
            }
            set {
                this.vibrateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string StartID {
            get {
                return this.startIDField;
            }
            set {
                this.startIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Thresh {
            get {
                return this.threshField;
            }
            set {
                this.threshField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Warning : ComplexType {
        
        private string vibrateField;
        
        private string throttleField;
        
        private string fltModeField;
        
        private string threshField;
        
        private string gyroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Vibrate {
            get {
                return this.vibrateField;
            }
            set {
                this.vibrateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Throttle {
            get {
                return this.throttleField;
            }
            set {
                this.throttleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FltMode {
            get {
                return this.fltModeField;
            }
            set {
                this.fltModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Thresh {
            get {
                return this.threshField;
            }
            set {
                this.threshField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Gyro {
            get {
                return this.gyroField;
            }
            set {
                this.gyroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Servo : ComplexType {
        
        private string indexField;
        
        private string sourceIDField;
        
        private string speedField;
        
        private string directionField;
        
        private string subTrimField;
        
        private string travelLowField;
        
        private string travelHighField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string sourceID {
            get {
                return this.sourceIDField;
            }
            set {
                this.sourceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string subTrim {
            get {
                return this.subTrimField;
            }
            set {
                this.subTrimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string travelLow {
            get {
                return this.travelLowField;
            }
            set {
                this.travelLowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string travelHigh {
            get {
                return this.travelHighField;
            }
            set {
                this.travelHighField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Trim : ComplexType {
        
        private string indexField;
        
        private string pos0Field;
        
        private string pos1Field;
        
        private string pos2Field;
        
        private string trimClicksField;
        
        private string maxTrimClicksField;
        
        private string trimStepSizeField;
        
        private string trimRepeatField;
        
        private string trimNextRepeatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos0 {
            get {
                return this.pos0Field;
            }
            set {
                this.pos0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos1 {
            get {
                return this.pos1Field;
            }
            set {
                this.pos1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos2 {
            get {
                return this.pos2Field;
            }
            set {
                this.pos2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string trimClicks {
            get {
                return this.trimClicksField;
            }
            set {
                this.trimClicksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string maxTrimClicks {
            get {
                return this.maxTrimClicksField;
            }
            set {
                this.maxTrimClicksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string trimStepSize {
            get {
                return this.trimStepSizeField;
            }
            set {
                this.trimStepSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string trimRepeat {
            get {
                return this.trimRepeatField;
            }
            set {
                this.trimRepeatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string trimNextRepeat {
            get {
                return this.trimNextRepeatField;
            }
            set {
                this.trimNextRepeatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class ThrottleCurve : ComplexType {
        
        private CurveData[] curvedataField;
        
        private string analogIDField;
        
        private string conditionIDField;
        
        private string trimIDField;
        
        private string activeMaskField;
        
        private string delayField;
        
        private string assignedCurveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Curvedata")]
        public CurveData[] Curvedata {
            get {
                return this.curvedataField;
            }
            set {
                this.curvedataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string analogID {
            get {
                return this.analogIDField;
            }
            set {
                this.analogIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string trimID {
            get {
                return this.trimIDField;
            }
            set {
                this.trimIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activeMask {
            get {
                return this.activeMaskField;
            }
            set {
                this.activeMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string delay {
            get {
                return this.delayField;
            }
            set {
                this.delayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assignedCurve {
            get {
                return this.assignedCurveField;
            }
            set {
                this.assignedCurveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class PMix : ComplexType {
        
        private CurveData[] curvedataField;
        
        private string indexField;
        
        private string analogIDField;
        
        private string conditionIDField;
        
        private string trimIDField;
        
        private string activePositionsField;
        
        private string outChanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Curvedata")]
        public CurveData[] Curvedata {
            get {
                return this.curvedataField;
            }
            set {
                this.curvedataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string analogID {
            get {
                return this.analogIDField;
            }
            set {
                this.analogIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string trimID {
            get {
                return this.trimIDField;
            }
            set {
                this.trimIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activePositions {
            get {
                return this.activePositionsField;
            }
            set {
                this.activePositionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string outChan {
            get {
                return this.outChanField;
            }
            set {
                this.outChanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class DualRateExpo : ComplexType {
        
        private string indexField;
        
        private string analogIDField;
        
        private string conditionIDField;
        
        private string activePositionsField;
        
        private string drHighField;
        
        private string drLowField;
        
        private string expoHighField;
        
        private string expoLowField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string analogID {
            get {
                return this.analogIDField;
            }
            set {
                this.analogIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activePositions {
            get {
                return this.activePositionsField;
            }
            set {
                this.activePositionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string drHigh {
            get {
                return this.drHighField;
            }
            set {
                this.drHighField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string drLow {
            get {
                return this.drLowField;
            }
            set {
                this.drLowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string expoHigh {
            get {
                return this.expoHighField;
            }
            set {
                this.expoHighField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string expoLow {
            get {
                return this.expoLowField;
            }
            set {
                this.expoLowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Digital : ComplexType {
        
        private string indexField;
        
        private string pos0Field;
        
        private string pos1Field;
        
        private string pos2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos0 {
            get {
                return this.pos0Field;
            }
            set {
                this.pos0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos1 {
            get {
                return this.pos1Field;
            }
            set {
                this.pos1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos2 {
            get {
                return this.pos2Field;
            }
            set {
                this.pos2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class IndexToSourceID : ComplexType {
        
        private string indexField;
        
        private string sourceIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string sourceID {
            get {
                return this.sourceIDField;
            }
            set {
                this.sourceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Analog : ComplexType {
        
        private string indexField;
        
        private string pos0Field;
        
        private string pos1Field;
        
        private string pos2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos0 {
            get {
                return this.pos0Field;
            }
            set {
                this.pos0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos1 {
            get {
                return this.pos1Field;
            }
            set {
                this.pos1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos2 {
            get {
                return this.pos2Field;
            }
            set {
                this.pos2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class FlightMode : ComplexType {
        
        private string switch_aField;
        
        private string switch_bField;
        
        private string switch_cField;
        
        private string sizeField;
        
        private string dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string switch_a {
            get {
                return this.switch_aField;
            }
            set {
                this.switch_aField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string switch_b {
            get {
                return this.switch_bField;
            }
            set {
                this.switch_bField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string switch_c {
            get {
                return this.switch_cField;
            }
            set {
                this.switch_cField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Trainer : ComplexType {
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Configuration : ComplexType {
        
        private string frameRateField;
        
        private string trimTypeField;
        
        private string trimModeField;
        
        public Configuration() {
            this.trimModeField = "Normal";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FrameRate {
            get {
                return this.frameRateField;
            }
            set {
                this.frameRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TrimType {
            get {
                return this.trimTypeField;
            }
            set {
                this.trimTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Normal")]
        public string trimMode {
            get {
                return this.trimModeField;
            }
            set {
                this.trimModeField = value;
            }
        }
    }
}
