//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace SPMReader.XSD {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/DX18.xsd")]
    public partial class Differential {
        
        private string conditionIDField;
        
        private string rateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/DX18.xsd")]
    public partial class AileronFlapsMixing {
        
        private string mixNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mixName {
            get {
                return this.mixNameField;
            }
            set {
                this.mixNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/DX18.xsd")]
    public partial class AileronRudderMixing {
        
        private string mixNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mixName {
            get {
                return this.mixNameField;
            }
            set {
                this.mixNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/DX18.xsd")]
    public partial class ElevatorFlapMxing {
        
        private string mixNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mixName {
            get {
                return this.mixNameField;
            }
            set {
                this.mixNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/DX18.xsd")]
    public partial class FlapElevatorMixing {
        
        private string analogIDField;
        
        private string conditionIDField;
        
        private string trimIDField;
        
        private string activeMaskField;
        
        private string delayField;
        
        private string mixNameField;
        
        private string assignedCurveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string analogID {
            get {
                return this.analogIDField;
            }
            set {
                this.analogIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string trimID {
            get {
                return this.trimIDField;
            }
            set {
                this.trimIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activeMask {
            get {
                return this.activeMaskField;
            }
            set {
                this.activeMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string delay {
            get {
                return this.delayField;
            }
            set {
                this.delayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mixName {
            get {
                return this.mixNameField;
            }
            set {
                this.mixNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assignedCurve {
            get {
                return this.assignedCurveField;
            }
            set {
                this.assignedCurveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/DX18.xsd")]
    public partial class SailPlaneInformation {
        
        private string wingField;
        
        private string tailField;
        
        private string motorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Wing {
            get {
                return this.wingField;
            }
            set {
                this.wingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tail {
            get {
                return this.tailField;
            }
            set {
                this.tailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Motor {
            get {
                return this.motorField;
            }
            set {
                this.motorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/DX18.xsd")]
    public partial class SpektrumInformation {
        
        private string generatorField;
        
        private string vCodeField;
        
        private string originatorField;
        
        private string posIndexField;
        
        private string posMaxSailField;
        
        private string typeField;
        
        private string curveIndexField;
        
        private string enabXPLUSField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VCode {
            get {
                return this.vCodeField;
            }
            set {
                this.vCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PosIndex {
            get {
                return this.posIndexField;
            }
            set {
                this.posIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PosMaxSail {
            get {
                return this.posMaxSailField;
            }
            set {
                this.posMaxSailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string curveIndex {
            get {
                return this.curveIndexField;
            }
            set {
                this.curveIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string enabXPLUS {
            get {
                return this.enabXPLUSField;
            }
            set {
                this.enabXPLUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/DX18.xsd")]
    public partial class SpektrumModel {
        
        private SpektrumInformation spektrumField;
        
        private SailPlaneInformation sailField;
        
        private FlapElevatorMixing flpEleMixField;
        
        private ElevatorFlapMxing eFMixField;
        
        private AileronRudderMixing aRMixSField;
        
        private AileronFlapsMixing aFMixSField;
        
        private Differential diffAilField;
        
        private Differential diffFlapField;
        
        private Differential diffTipField;
        
        private Differential diffRudField;
        
        private object camberMixField;
        
        private object camberPresetField;
        
        private object configField;
        
        private object trainerField;
        
        private object fModeField;
        
        private object analogField;
        
        private object[] specialField;
        
        private object[] softSwField;
        
        private object[] trimIDField;
        
        private object[] digitalField;
        
        private object[] trimField;
        
        private object[] servoField;
        
        private object[] dR_ExpoField;
        
        private object[] pMixField;
        
        private object throCutField;
        
        private object throCurveField;
        
        private object warningField;
        
        private object timerField;
        
        private object telemetryField;
        
        private object preflightField;
        
        private object fMode_NamesField;
        
        /// <remarks/>
        public SpektrumInformation Spektrum {
            get {
                return this.spektrumField;
            }
            set {
                this.spektrumField = value;
            }
        }
        
        /// <remarks/>
        public SailPlaneInformation Sail {
            get {
                return this.sailField;
            }
            set {
                this.sailField = value;
            }
        }
        
        /// <remarks/>
        public FlapElevatorMixing FlpEleMix {
            get {
                return this.flpEleMixField;
            }
            set {
                this.flpEleMixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EF-Mix")]
        public ElevatorFlapMxing EFMix {
            get {
                return this.eFMixField;
            }
            set {
                this.eFMixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AR-Mix-S")]
        public AileronRudderMixing ARMixS {
            get {
                return this.aRMixSField;
            }
            set {
                this.aRMixSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AF-Mix-S")]
        public AileronFlapsMixing AFMixS {
            get {
                return this.aFMixSField;
            }
            set {
                this.aFMixSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Diff-Ail")]
        public Differential DiffAil {
            get {
                return this.diffAilField;
            }
            set {
                this.diffAilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Diff-Flap")]
        public Differential DiffFlap {
            get {
                return this.diffFlapField;
            }
            set {
                this.diffFlapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Diff-Tip")]
        public Differential DiffTip {
            get {
                return this.diffTipField;
            }
            set {
                this.diffTipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Diff-Rud")]
        public Differential DiffRud {
            get {
                return this.diffRudField;
            }
            set {
                this.diffRudField = value;
            }
        }
        
        /// <remarks/>
        public object CamberMix {
            get {
                return this.camberMixField;
            }
            set {
                this.camberMixField = value;
            }
        }
        
        /// <remarks/>
        public object CamberPreset {
            get {
                return this.camberPresetField;
            }
            set {
                this.camberPresetField = value;
            }
        }
        
        /// <remarks/>
        public object Config {
            get {
                return this.configField;
            }
            set {
                this.configField = value;
            }
        }
        
        /// <remarks/>
        public object Trainer {
            get {
                return this.trainerField;
            }
            set {
                this.trainerField = value;
            }
        }
        
        /// <remarks/>
        public object FMode {
            get {
                return this.fModeField;
            }
            set {
                this.fModeField = value;
            }
        }
        
        /// <remarks/>
        public object Analog {
            get {
                return this.analogField;
            }
            set {
                this.analogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Special")]
        public object[] Special {
            get {
                return this.specialField;
            }
            set {
                this.specialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoftSw")]
        public object[] SoftSw {
            get {
                return this.softSwField;
            }
            set {
                this.softSwField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TrimID")]
        public object[] TrimID {
            get {
                return this.trimIDField;
            }
            set {
                this.trimIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Digital")]
        public object[] Digital {
            get {
                return this.digitalField;
            }
            set {
                this.digitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Trim")]
        public object[] Trim {
            get {
                return this.trimField;
            }
            set {
                this.trimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Servo")]
        public object[] Servo {
            get {
                return this.servoField;
            }
            set {
                this.servoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DR_Expo")]
        public object[] DR_Expo {
            get {
                return this.dR_ExpoField;
            }
            set {
                this.dR_ExpoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("P-Mix")]
        public object[] PMix {
            get {
                return this.pMixField;
            }
            set {
                this.pMixField = value;
            }
        }
        
        /// <remarks/>
        public object ThroCut {
            get {
                return this.throCutField;
            }
            set {
                this.throCutField = value;
            }
        }
        
        /// <remarks/>
        public object ThroCurve {
            get {
                return this.throCurveField;
            }
            set {
                this.throCurveField = value;
            }
        }
        
        /// <remarks/>
        public object Warning {
            get {
                return this.warningField;
            }
            set {
                this.warningField = value;
            }
        }
        
        /// <remarks/>
        public object Timer {
            get {
                return this.timerField;
            }
            set {
                this.timerField = value;
            }
        }
        
        /// <remarks/>
        public object Telemetry {
            get {
                return this.telemetryField;
            }
            set {
                this.telemetryField = value;
            }
        }
        
        /// <remarks/>
        public object Preflight {
            get {
                return this.preflightField;
            }
            set {
                this.preflightField = value;
            }
        }
        
        /// <remarks/>
        public object FMode_Names {
            get {
                return this.fMode_NamesField;
            }
            set {
                this.fMode_NamesField = value;
            }
        }
    }
}
