//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace SPMReader.Models.Spektrum {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpektrumModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/ModelDescription.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:SPMReader/ModelDescription.xsd", IsNullable=false)]
    public abstract partial class Model {
        
        private ModelDescription modelDescriptionField;
        
        /// <remarks/>
        public ModelDescription ModelDescription {
            get {
                return this.modelDescriptionField;
            }
            set {
                this.modelDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/ModelDescription.xsd")]
    public partial class ModelDescription {
        
        private string prefixModelTextField;
        
        private string postfixModelTextField;
        
        private string eOFMarkerTextField;
        
        private string newLineMarkerField;
        
        public ModelDescription() {
            this.eOFMarkerTextField = "*EOF*";
        }
        
        /// <remarks/>
        public string PrefixModelText {
            get {
                return this.prefixModelTextField;
            }
            set {
                this.prefixModelTextField = value;
            }
        }
        
        /// <remarks/>
        public string PostfixModelText {
            get {
                return this.postfixModelTextField;
            }
            set {
                this.postfixModelTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("*EOF*")]
        public string EOFMarkerText {
            get {
                return this.eOFMarkerTextField;
            }
            set {
                this.eOFMarkerTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewLineMarker {
            get {
                return this.newLineMarkerField;
            }
            set {
                this.newLineMarkerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/ModelDescription.xsd")]
    public partial class Descriptor {
        
        private string separatorStyleField;
        
        private bool isStringField;
        
        private string attributeNameField;
        
        private bool valueHasPreceedingSpaceField;
        
        private string prefixValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SeparatorStyle {
            get {
                return this.separatorStyleField;
            }
            set {
                this.separatorStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsString {
            get {
                return this.isStringField;
            }
            set {
                this.isStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ValueHasPreceedingSpace {
            get {
                return this.valueHasPreceedingSpaceField;
            }
            set {
                this.valueHasPreceedingSpaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PrefixValue {
            get {
                return this.prefixValueField;
            }
            set {
                this.prefixValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd", IsNullable=false)]
    public partial class SpektrumModel : Model {
        
        private SpektrumInformation spektrumField;
        
        private Configuration configField;
        
        private Trainer trainerField;
        
        private FlightMode fModeField;
        
        private Analog[] analogField;
        
        private IndexToSourceID[] specialField;
        
        private IndexToSourceID[] softSwField;
        
        private IndexToSourceID[] trimIDField;
        
        private Digital[] digitalField;
        
        private Trim[] trimField;
        
        private Servo[] servoField;
        
        private DualRateExpo[] dR_ExpoField;
        
        private PMix[] pMixField;
        
        private ThrottleCut throCutField;
        
        private ThrottleCurve throCurveField;
        
        private Warning warningField;
        
        private Timer[] timerField;
        
        private Telemetry telemetryField;
        
        /// <remarks/>
        public SpektrumInformation Spektrum {
            get {
                return this.spektrumField;
            }
            set {
                this.spektrumField = value;
            }
        }
        
        /// <remarks/>
        public Configuration Config {
            get {
                return this.configField;
            }
            set {
                this.configField = value;
            }
        }
        
        /// <remarks/>
        public Trainer Trainer {
            get {
                return this.trainerField;
            }
            set {
                this.trainerField = value;
            }
        }
        
        /// <remarks/>
        public FlightMode FMode {
            get {
                return this.fModeField;
            }
            set {
                this.fModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Analog")]
        public Analog[] Analog {
            get {
                return this.analogField;
            }
            set {
                this.analogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Special")]
        public IndexToSourceID[] Special {
            get {
                return this.specialField;
            }
            set {
                this.specialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoftSw")]
        public IndexToSourceID[] SoftSw {
            get {
                return this.softSwField;
            }
            set {
                this.softSwField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TrimID")]
        public IndexToSourceID[] TrimID {
            get {
                return this.trimIDField;
            }
            set {
                this.trimIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Digital")]
        public Digital[] Digital {
            get {
                return this.digitalField;
            }
            set {
                this.digitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Trim")]
        public Trim[] Trim {
            get {
                return this.trimField;
            }
            set {
                this.trimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Servo")]
        public Servo[] Servo {
            get {
                return this.servoField;
            }
            set {
                this.servoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DR_Expo")]
        public DualRateExpo[] DR_Expo {
            get {
                return this.dR_ExpoField;
            }
            set {
                this.dR_ExpoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("P-Mix")]
        public PMix[] PMix {
            get {
                return this.pMixField;
            }
            set {
                this.pMixField = value;
            }
        }
        
        /// <remarks/>
        public ThrottleCut ThroCut {
            get {
                return this.throCutField;
            }
            set {
                this.throCutField = value;
            }
        }
        
        /// <remarks/>
        public ThrottleCurve ThroCurve {
            get {
                return this.throCurveField;
            }
            set {
                this.throCurveField = value;
            }
        }
        
        /// <remarks/>
        public Warning Warning {
            get {
                return this.warningField;
            }
            set {
                this.warningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Timer")]
        public Timer[] Timer {
            get {
                return this.timerField;
            }
            set {
                this.timerField = value;
            }
        }
        
        /// <remarks/>
        public Telemetry Telemetry {
            get {
                return this.telemetryField;
            }
            set {
                this.telemetryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class SpektrumInformation : ComplexType {
        
        private string generatorField;
        
        private string vCodeField;
        
        private string originatorField;
        
        private string posIndexField;
        
        private string posMaxSailField;
        
        private string typeField;
        
        private string curveIndexField;
        
        private string enabXPLUSField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VCode {
            get {
                return this.vCodeField;
            }
            set {
                this.vCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PosIndex {
            get {
                return this.posIndexField;
            }
            set {
                this.posIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PosMaxSail {
            get {
                return this.posMaxSailField;
            }
            set {
                this.posMaxSailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string curveIndex {
            get {
                return this.curveIndexField;
            }
            set {
                this.curveIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string enabXPLUS {
            get {
                return this.enabXPLUSField;
            }
            set {
                this.enabXPLUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TelemetryModule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FlightLog))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Telemetry))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Timer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Warning))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Servo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Trim))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ThrottleCurve))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ThrottleCut))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PMix))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DualRateExpo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Digital))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IndexToSourceID))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Analog))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FlightMode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Trainer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Configuration))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CurveData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpektrumInformation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/ModelDescription.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:SPMReader/ModelDescription.xsd", IsNullable=false)]
    public abstract partial class ComplexType {
        
        private Descriptor[] attributeDescriptorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Descriptor[] AttributeDescriptors {
            get {
                return this.attributeDescriptorsField;
            }
            set {
                this.attributeDescriptorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class TelemetryModule : ComplexType {
        
        private string deviceField;
        
        private string minAltitudeField;
        
        private string maxAltitudeField;
        
        private string minAlarmField;
        
        private string maxAlarmField;
        
        private string addressField;
        
        private string displayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string minAltitude {
            get {
                return this.minAltitudeField;
            }
            set {
                this.minAltitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string maxAltitude {
            get {
                return this.maxAltitudeField;
            }
            set {
                this.maxAltitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string minAlarm {
            get {
                return this.minAlarmField;
            }
            set {
                this.minAlarmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string maxAlarm {
            get {
                return this.maxAlarmField;
            }
            set {
                this.maxAlarmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string display {
            get {
                return this.displayField;
            }
            set {
                this.displayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class FlightLog : ComplexType {
        
        private string fField;
        
        private string hField;
        
        private string aField;
        
        private string bField;
        
        private string rField;
        
        private string lField;
        
        private string frameAlarmField;
        
        private string holdAlarmField;
        
        private string minRxField;
        
        private string maxRxField;
        
        private string rxVoltAlarmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string F {
            get {
                return this.fField;
            }
            set {
                this.fField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string H {
            get {
                return this.hField;
            }
            set {
                this.hField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string A {
            get {
                return this.aField;
            }
            set {
                this.aField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string B {
            get {
                return this.bField;
            }
            set {
                this.bField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string R {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string L {
            get {
                return this.lField;
            }
            set {
                this.lField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FrameAlarm {
            get {
                return this.frameAlarmField;
            }
            set {
                this.frameAlarmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HoldAlarm {
            get {
                return this.holdAlarmField;
            }
            set {
                this.holdAlarmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string minRx {
            get {
                return this.minRxField;
            }
            set {
                this.minRxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string maxRx {
            get {
                return this.maxRxField;
            }
            set {
                this.maxRxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RxVoltAlarm {
            get {
                return this.rxVoltAlarmField;
            }
            set {
                this.rxVoltAlarmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Telemetry : ComplexType {
        
        private FlightLog flightLogField;
        
        private TelemetryModule[] moduleField;
        
        private string lcdModeField;
        
        private string screensField;
        
        private string startIDField;
        
        private string eventField;
        
        private string threshField;
        
        private string oneTimeField;
        
        /// <remarks/>
        public FlightLog FlightLog {
            get {
                return this.flightLogField;
            }
            set {
                this.flightLogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Module")]
        public TelemetryModule[] Module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string lcdMode {
            get {
                return this.lcdModeField;
            }
            set {
                this.lcdModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Screens {
            get {
                return this.screensField;
            }
            set {
                this.screensField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string StartID {
            get {
                return this.startIDField;
            }
            set {
                this.startIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Thresh {
            get {
                return this.threshField;
            }
            set {
                this.threshField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string oneTime {
            get {
                return this.oneTimeField;
            }
            set {
                this.oneTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Timer : ComplexType {
        
        private string indexField;
        
        private string modeField;
        
        private string minutesField;
        
        private string secondsField;
        
        private string oneTimeField;
        
        private string audioField;
        
        private string vibrateField;
        
        private string startIDField;
        
        private string eventField;
        
        private string threshField;
        
        private string activePositionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Minutes {
            get {
                return this.minutesField;
            }
            set {
                this.minutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string oneTime {
            get {
                return this.oneTimeField;
            }
            set {
                this.oneTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Audio {
            get {
                return this.audioField;
            }
            set {
                this.audioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Vibrate {
            get {
                return this.vibrateField;
            }
            set {
                this.vibrateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string StartID {
            get {
                return this.startIDField;
            }
            set {
                this.startIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Thresh {
            get {
                return this.threshField;
            }
            set {
                this.threshField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activePositions {
            get {
                return this.activePositionsField;
            }
            set {
                this.activePositionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Warning : ComplexType {
        
        private string vibrateField;
        
        private string spoilerField;
        
        private string fltModeField;
        
        private string gearField;
        
        private string motorField;
        
        private string chanAchanField;
        
        private string chanAtypeField;
        
        private string chanBchanField;
        
        private string chanBtypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Vibrate {
            get {
                return this.vibrateField;
            }
            set {
                this.vibrateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Spoiler {
            get {
                return this.spoilerField;
            }
            set {
                this.spoilerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FltMode {
            get {
                return this.fltModeField;
            }
            set {
                this.fltModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Gear {
            get {
                return this.gearField;
            }
            set {
                this.gearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Motor {
            get {
                return this.motorField;
            }
            set {
                this.motorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string chanAchan {
            get {
                return this.chanAchanField;
            }
            set {
                this.chanAchanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chanAtype {
            get {
                return this.chanAtypeField;
            }
            set {
                this.chanAtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string chanBchan {
            get {
                return this.chanBchanField;
            }
            set {
                this.chanBchanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chanBtype {
            get {
                return this.chanBtypeField;
            }
            set {
                this.chanBtypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Servo : ComplexType {
        
        private CurveData[] curvedataField;
        
        private string indexField;
        
        private string sourceIDField;
        
        private string speedField;
        
        private string conditionIDField;
        
        private string activePositionsField;
        
        private string speedDownField;
        
        private string absLimitHighField;
        
        private string directionField;
        
        private string subTrimField;
        
        private string travelLowField;
        
        private string travelHighField;
        
        private string nameField;
        
        private string vSourceField;
        
        private string absLimitLowField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Curvedata")]
        public CurveData[] Curvedata {
            get {
                return this.curvedataField;
            }
            set {
                this.curvedataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string sourceID {
            get {
                return this.sourceIDField;
            }
            set {
                this.sourceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activePositions {
            get {
                return this.activePositionsField;
            }
            set {
                this.activePositionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string speedDown {
            get {
                return this.speedDownField;
            }
            set {
                this.speedDownField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string absLimitHigh {
            get {
                return this.absLimitHighField;
            }
            set {
                this.absLimitHighField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string subTrim {
            get {
                return this.subTrimField;
            }
            set {
                this.subTrimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string travelLow {
            get {
                return this.travelLowField;
            }
            set {
                this.travelLowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string travelHigh {
            get {
                return this.travelHighField;
            }
            set {
                this.travelHighField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string vSource {
            get {
                return this.vSourceField;
            }
            set {
                this.vSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string absLimitLow {
            get {
                return this.absLimitLowField;
            }
            set {
                this.absLimitLowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class CurveData : ComplexType {
        
        private string indexField;
        
        private string pointsField;
        
        private string expoField;
        
        private string trimActiveField;
        
        private string curvedField;
        
        private string xField;
        
        private string yField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string points {
            get {
                return this.pointsField;
            }
            set {
                this.pointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Expo {
            get {
                return this.expoField;
            }
            set {
                this.expoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string trimActive {
            get {
                return this.trimActiveField;
            }
            set {
                this.trimActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string curved {
            get {
                return this.curvedField;
            }
            set {
                this.curvedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Trim : ComplexType {
        
        private string indexField;
        
        private string pos0Field;
        
        private string pos1Field;
        
        private string pos2Field;
        
        private string trimClicksField;
        
        private string maxTrimClicksField;
        
        private string trimStepSizeField;
        
        private string trimRepeatField;
        
        private string trimNextRepeatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos0 {
            get {
                return this.pos0Field;
            }
            set {
                this.pos0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos1 {
            get {
                return this.pos1Field;
            }
            set {
                this.pos1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos2 {
            get {
                return this.pos2Field;
            }
            set {
                this.pos2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string trimClicks {
            get {
                return this.trimClicksField;
            }
            set {
                this.trimClicksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string maxTrimClicks {
            get {
                return this.maxTrimClicksField;
            }
            set {
                this.maxTrimClicksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string trimStepSize {
            get {
                return this.trimStepSizeField;
            }
            set {
                this.trimStepSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string trimRepeat {
            get {
                return this.trimRepeatField;
            }
            set {
                this.trimRepeatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string trimNextRepeat {
            get {
                return this.trimNextRepeatField;
            }
            set {
                this.trimNextRepeatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class ThrottleCurve : ComplexType {
        
        private CurveData[] curvedataField;
        
        private string analogIDField;
        
        private string conditionIDField;
        
        private string trimIDField;
        
        private string activeMaskField;
        
        private string delayField;
        
        private string mixNameField;
        
        private string assignedCurveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Curvedata")]
        public CurveData[] Curvedata {
            get {
                return this.curvedataField;
            }
            set {
                this.curvedataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string analogID {
            get {
                return this.analogIDField;
            }
            set {
                this.analogIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string trimID {
            get {
                return this.trimIDField;
            }
            set {
                this.trimIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activeMask {
            get {
                return this.activeMaskField;
            }
            set {
                this.activeMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string delay {
            get {
                return this.delayField;
            }
            set {
                this.delayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mixName {
            get {
                return this.mixNameField;
            }
            set {
                this.mixNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assignedCurve {
            get {
                return this.assignedCurveField;
            }
            set {
                this.assignedCurveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class ThrottleCut : ComplexType {
        
        private string conditionIDField;
        
        private string percentField;
        
        private string rampSpeedField;
        
        private string activePositionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string percent {
            get {
                return this.percentField;
            }
            set {
                this.percentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string rampSpeed {
            get {
                return this.rampSpeedField;
            }
            set {
                this.rampSpeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activePositions {
            get {
                return this.activePositionsField;
            }
            set {
                this.activePositionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class PMix : ComplexType {
        
        private CurveData[] curvedataField;
        
        private string indexField;
        
        private string analogIDField;
        
        private string conditionIDField;
        
        private string trimIDField;
        
        private string activePositionsField;
        
        private string conditionID1Field;
        
        private string conditionID2Field;
        
        private string activePositions1Field;
        
        private string activePositions2Field;
        
        private string relationField;
        
        private string outChanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Curvedata")]
        public CurveData[] Curvedata {
            get {
                return this.curvedataField;
            }
            set {
                this.curvedataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string analogID {
            get {
                return this.analogIDField;
            }
            set {
                this.analogIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string trimID {
            get {
                return this.trimIDField;
            }
            set {
                this.trimIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activePositions {
            get {
                return this.activePositionsField;
            }
            set {
                this.activePositionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string conditionID1 {
            get {
                return this.conditionID1Field;
            }
            set {
                this.conditionID1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string conditionID2 {
            get {
                return this.conditionID2Field;
            }
            set {
                this.conditionID2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activePositions1 {
            get {
                return this.activePositions1Field;
            }
            set {
                this.activePositions1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activePositions2 {
            get {
                return this.activePositions2Field;
            }
            set {
                this.activePositions2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string relation {
            get {
                return this.relationField;
            }
            set {
                this.relationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string outChan {
            get {
                return this.outChanField;
            }
            set {
                this.outChanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class DualRateExpo : ComplexType {
        
        private string indexField;
        
        private string analogIDField;
        
        private string conditionIDField;
        
        private string activePositionsField;
        
        private string drHighField;
        
        private string drLowField;
        
        private string drHigh1Field;
        
        private string drLow1Field;
        
        private string drHigh2Field;
        
        private string drLow2Field;
        
        private string expoHighField;
        
        private string assignedCurveField;
        
        private string expoLowField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string analogID {
            get {
                return this.analogIDField;
            }
            set {
                this.analogIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activePositions {
            get {
                return this.activePositionsField;
            }
            set {
                this.activePositionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string drHigh {
            get {
                return this.drHighField;
            }
            set {
                this.drHighField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string drLow {
            get {
                return this.drLowField;
            }
            set {
                this.drLowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string drHigh1 {
            get {
                return this.drHigh1Field;
            }
            set {
                this.drHigh1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string drLow1 {
            get {
                return this.drLow1Field;
            }
            set {
                this.drLow1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string drHigh2 {
            get {
                return this.drHigh2Field;
            }
            set {
                this.drHigh2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string drLow2 {
            get {
                return this.drLow2Field;
            }
            set {
                this.drLow2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string expoHigh {
            get {
                return this.expoHighField;
            }
            set {
                this.expoHighField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assignedCurve {
            get {
                return this.assignedCurveField;
            }
            set {
                this.assignedCurveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string expoLow {
            get {
                return this.expoLowField;
            }
            set {
                this.expoLowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Digital : ComplexType {
        
        private string indexField;
        
        private string pos0Field;
        
        private string pos1Field;
        
        private string pos2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos0 {
            get {
                return this.pos0Field;
            }
            set {
                this.pos0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos1 {
            get {
                return this.pos1Field;
            }
            set {
                this.pos1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos2 {
            get {
                return this.pos2Field;
            }
            set {
                this.pos2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class IndexToSourceID : ComplexType {
        
        private string indexField;
        
        private string sourceIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string sourceID {
            get {
                return this.sourceIDField;
            }
            set {
                this.sourceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Analog : ComplexType {
        
        private string indexField;
        
        private string pos0Field;
        
        private string pos1Field;
        
        private string pos2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos0 {
            get {
                return this.pos0Field;
            }
            set {
                this.pos0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos1 {
            get {
                return this.pos1Field;
            }
            set {
                this.pos1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Pos2 {
            get {
                return this.pos2Field;
            }
            set {
                this.pos2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class FlightMode : ComplexType {
        
        private string switch_aField;
        
        private string switch_bField;
        
        private string switch_cField;
        
        private string switch_dField;
        
        private string priority0Field;
        
        private string priority1Field;
        
        private string priority2Field;
        
        private string sizeField;
        
        private string fmtableField;
        
        private string activePositionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string switch_a {
            get {
                return this.switch_aField;
            }
            set {
                this.switch_aField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string switch_b {
            get {
                return this.switch_bField;
            }
            set {
                this.switch_bField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string switch_c {
            get {
                return this.switch_cField;
            }
            set {
                this.switch_cField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string switch_d {
            get {
                return this.switch_dField;
            }
            set {
                this.switch_dField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string priority0 {
            get {
                return this.priority0Field;
            }
            set {
                this.priority0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string priority1 {
            get {
                return this.priority1Field;
            }
            set {
                this.priority1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string priority2 {
            get {
                return this.priority2Field;
            }
            set {
                this.priority2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fmtable {
            get {
                return this.fmtableField;
            }
            set {
                this.fmtableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string activePositions {
            get {
                return this.activePositionsField;
            }
            set {
                this.activePositionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Trainer : ComplexType {
        
        private string conditionIDField;
        
        private string typeField;
        
        private string mOverrideField;
        
        private string activePositionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string conditionID {
            get {
                return this.conditionIDField;
            }
            set {
                this.conditionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MOverride {
            get {
                return this.mOverrideField;
            }
            set {
                this.mOverrideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string activePositions {
            get {
                return this.activePositionsField;
            }
            set {
                this.activePositionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:SPMReader/Spektrum/Spektrum.xsd")]
    public partial class Configuration : ComplexType {
        
        private string frameRateField;
        
        private string trimTypeField;
        
        private string trimModeField;
        
        public Configuration() {
            this.trimModeField = "Normal";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FrameRate {
            get {
                return this.frameRateField;
            }
            set {
                this.frameRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TrimType {
            get {
                return this.trimTypeField;
            }
            set {
                this.trimTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Normal")]
        public string trimMode {
            get {
                return this.trimModeField;
            }
            set {
                this.trimModeField = value;
            }
        }
    }
}
